{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "880ade08",
   "metadata": {},
   "outputs": [],
   "source": [
    "#data visualization\n",
    "import folium\n",
    "\n",
    "#위도\n",
    "latitude = 35.15507631561923\n",
    "\n",
    "#경도\n",
    "longitude = 129.00027388788675\n",
    "\n",
    "m = folium.Map(location=[latitude, longitude],\n",
    "              zoom_start=20,\n",
    "              width=750,\n",
    "              height=500)\n",
    "\n",
    "#m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7efde7d9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<folium.map.Marker at 0x2c83d66d570>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "folium.Marker([latitude, longitude],\n",
    "              popup='주례청구', #클릭했을 때\n",
    "              tooltip='주례청구아파트',  #마우스 올렸을 때\n",
    "              icon=folium.Icon('red',icon='heart'), #아이콘색 / 모양 변경\n",
    "              ).add_to(m)\n",
    "\n",
    "#m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9c2985a0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<folium.vector_layers.CircleMarker at 0x2c845e8b340>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "folium.CircleMarker([latitude, longitude],\n",
    "                   color='tomato',\n",
    "                   radius = 50,\n",
    "                   tooltip='주례청구아파트 상권').add_to(m)\n",
    "\n",
    "#m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "50834b81",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv('소상공인시장진흥공단_상가(상권)정보_부산_202206.csv', encoding='cp949')\n",
    "\n",
    "#df.head(3)  #3개만 출력"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c05cdd0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#pd.Series(df.columns)  #인덱스 확인"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c0ac7d64",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>상가업소번호</th>\n",
       "      <th>상호명</th>\n",
       "      <th>지점명</th>\n",
       "      <th>상권업종대분류코드</th>\n",
       "      <th>상권업종대분류명</th>\n",
       "      <th>상권업종중분류코드</th>\n",
       "      <th>상권업종중분류명</th>\n",
       "      <th>상권업종소분류코드</th>\n",
       "      <th>상권업종소분류명</th>\n",
       "      <th>표준산업분류코드</th>\n",
       "      <th>...</th>\n",
       "      <th>건물관리번호</th>\n",
       "      <th>건물명</th>\n",
       "      <th>도로명주소</th>\n",
       "      <th>구우편번호</th>\n",
       "      <th>신우편번호</th>\n",
       "      <th>동정보</th>\n",
       "      <th>층정보</th>\n",
       "      <th>호정보</th>\n",
       "      <th>경도</th>\n",
       "      <th>위도</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>24352260</td>\n",
       "      <td>엑시아골프</td>\n",
       "      <td>NaN</td>\n",
       "      <td>D</td>\n",
       "      <td>소매</td>\n",
       "      <td>D14</td>\n",
       "      <td>운동/경기용품소매</td>\n",
       "      <td>D14A01</td>\n",
       "      <td>운동/경기용품</td>\n",
       "      <td>G47631</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>NaN</td>\n",
       "      <td>부산광역시 북구 금곡대로616번길 142</td>\n",
       "      <td>616810</td>\n",
       "      <td>46505.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.017912</td>\n",
       "      <td>35.266739</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>22477130</td>\n",
       "      <td>동백주유소</td>\n",
       "      <td>NaN</td>\n",
       "      <td>F</td>\n",
       "      <td>생활서비스</td>\n",
       "      <td>F16</td>\n",
       "      <td>주유소/충전소</td>\n",
       "      <td>F16A01</td>\n",
       "      <td>주유소</td>\n",
       "      <td>G47711</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>현대오일뱅크주유소</td>\n",
       "      <td>부산광역시 북구 금곡대로 712</td>\n",
       "      <td>616810</td>\n",
       "      <td>46510.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.018756</td>\n",
       "      <td>35.270076</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>233</th>\n",
       "      <td>23973390</td>\n",
       "      <td>향수&amp;화장품</td>\n",
       "      <td>NaN</td>\n",
       "      <td>D</td>\n",
       "      <td>소매</td>\n",
       "      <td>D16</td>\n",
       "      <td>화장품소매</td>\n",
       "      <td>D16A01</td>\n",
       "      <td>화장품판매점</td>\n",
       "      <td>G47813</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>금곡2단지주공아파트</td>\n",
       "      <td>부산광역시 북구 금곡대로616번길 10-5</td>\n",
       "      <td>616762</td>\n",
       "      <td>46507.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.015256</td>\n",
       "      <td>35.261768</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>263</th>\n",
       "      <td>24280534</td>\n",
       "      <td>형제식품</td>\n",
       "      <td>NaN</td>\n",
       "      <td>D</td>\n",
       "      <td>소매</td>\n",
       "      <td>D01</td>\n",
       "      <td>음/식료품소매</td>\n",
       "      <td>D01A01</td>\n",
       "      <td>식료품점</td>\n",
       "      <td>G47219</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>화명리버빌아파트</td>\n",
       "      <td>부산광역시 북구 화명신도시로 244</td>\n",
       "      <td>616775</td>\n",
       "      <td>46520.0</td>\n",
       "      <td>208</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.011425</td>\n",
       "      <td>35.245269</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>333</th>\n",
       "      <td>24195816</td>\n",
       "      <td>이편한낚시</td>\n",
       "      <td>NaN</td>\n",
       "      <td>D</td>\n",
       "      <td>소매</td>\n",
       "      <td>D14</td>\n",
       "      <td>운동/경기용품소매</td>\n",
       "      <td>D14A01</td>\n",
       "      <td>운동/경기용품</td>\n",
       "      <td>G47631</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>금곡월드프라자</td>\n",
       "      <td>부산광역시 북구 금곡대로 458</td>\n",
       "      <td>616813</td>\n",
       "      <td>46509.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.013319</td>\n",
       "      <td>35.249129</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151739</th>\n",
       "      <td>18507025</td>\n",
       "      <td>건미수다올</td>\n",
       "      <td>NaN</td>\n",
       "      <td>D</td>\n",
       "      <td>소매</td>\n",
       "      <td>D16</td>\n",
       "      <td>화장품소매</td>\n",
       "      <td>D16A01</td>\n",
       "      <td>화장품판매점</td>\n",
       "      <td>G47813</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>금곡동디온빌</td>\n",
       "      <td>부산광역시 북구 효열로219번다길 3</td>\n",
       "      <td>616810</td>\n",
       "      <td>46506.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.017838</td>\n",
       "      <td>35.264342</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151761</th>\n",
       "      <td>18513087</td>\n",
       "      <td>땅스부대찌개부산</td>\n",
       "      <td>금곡율리점</td>\n",
       "      <td>Q</td>\n",
       "      <td>음식</td>\n",
       "      <td>Q01</td>\n",
       "      <td>한식</td>\n",
       "      <td>Q01A05</td>\n",
       "      <td>해장국/감자탕</td>\n",
       "      <td>I56111</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>율리벽산블루밍아파트</td>\n",
       "      <td>부산광역시 북구 효열로 1</td>\n",
       "      <td>616841</td>\n",
       "      <td>46509.0</td>\n",
       "      <td>상가</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.013943</td>\n",
       "      <td>35.248925</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151792</th>\n",
       "      <td>18518646</td>\n",
       "      <td>이선산업</td>\n",
       "      <td>NaN</td>\n",
       "      <td>F</td>\n",
       "      <td>생활서비스</td>\n",
       "      <td>F15</td>\n",
       "      <td>주택수리</td>\n",
       "      <td>F15A02</td>\n",
       "      <td>미장타일도배도장</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>NaN</td>\n",
       "      <td>부산광역시 북구 효열로203번가길 39</td>\n",
       "      <td>616810</td>\n",
       "      <td>46506.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.017314</td>\n",
       "      <td>35.264599</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151961</th>\n",
       "      <td>18518270</td>\n",
       "      <td>영진이엔에스</td>\n",
       "      <td>NaN</td>\n",
       "      <td>D</td>\n",
       "      <td>소매</td>\n",
       "      <td>D02</td>\n",
       "      <td>선물/팬시/기념품</td>\n",
       "      <td>D02A02</td>\n",
       "      <td>꽃집/꽃배달</td>\n",
       "      <td>G47851</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>금곡2단지주공아파트</td>\n",
       "      <td>부산광역시 북구 금곡대로616번길 10-7</td>\n",
       "      <td>616762</td>\n",
       "      <td>46507.0</td>\n",
       "      <td>7701</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.015221</td>\n",
       "      <td>35.261597</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>152063</th>\n",
       "      <td>18524616</td>\n",
       "      <td>화이트펜슬부산</td>\n",
       "      <td>율리점</td>\n",
       "      <td>R</td>\n",
       "      <td>학문/교육</td>\n",
       "      <td>R10</td>\n",
       "      <td>도서관/독서실</td>\n",
       "      <td>R10A01</td>\n",
       "      <td>독서실</td>\n",
       "      <td>R90212</td>\n",
       "      <td>...</td>\n",
       "      <td>2.632010e+24</td>\n",
       "      <td>삼화빌딩</td>\n",
       "      <td>부산광역시 북구 금곡대로 441</td>\n",
       "      <td>616841</td>\n",
       "      <td>46519.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>129.012664</td>\n",
       "      <td>35.247728</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>677 rows × 39 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          상가업소번호       상호명    지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드   상권업종중분류명  \\\n",
       "33      24352260     엑시아골프    NaN         D       소매       D14  운동/경기용품소매   \n",
       "112     22477130     동백주유소    NaN         F    생활서비스       F16    주유소/충전소   \n",
       "233     23973390    향수&화장품    NaN         D       소매       D16      화장품소매   \n",
       "263     24280534      형제식품    NaN         D       소매       D01    음/식료품소매   \n",
       "333     24195816     이편한낚시    NaN         D       소매       D14  운동/경기용품소매   \n",
       "...          ...       ...    ...       ...      ...       ...        ...   \n",
       "151739  18507025     건미수다올    NaN         D       소매       D16      화장품소매   \n",
       "151761  18513087  땅스부대찌개부산  금곡율리점         Q       음식       Q01         한식   \n",
       "151792  18518646      이선산업    NaN         F    생활서비스       F15       주택수리   \n",
       "151961  18518270    영진이엔에스    NaN         D       소매       D02  선물/팬시/기념품   \n",
       "152063  18524616   화이트펜슬부산    율리점         R    학문/교육       R10    도서관/독서실   \n",
       "\n",
       "       상권업종소분류코드  상권업종소분류명 표준산업분류코드  ...        건물관리번호         건물명  \\\n",
       "33        D14A01   운동/경기용품   G47631  ...  2.632010e+24         NaN   \n",
       "112       F16A01       주유소   G47711  ...  2.632010e+24   현대오일뱅크주유소   \n",
       "233       D16A01    화장품판매점   G47813  ...  2.632010e+24  금곡2단지주공아파트   \n",
       "263       D01A01      식료품점   G47219  ...  2.632010e+24    화명리버빌아파트   \n",
       "333       D14A01   운동/경기용품   G47631  ...  2.632010e+24     금곡월드프라자   \n",
       "...          ...       ...      ...  ...           ...         ...   \n",
       "151739    D16A01    화장품판매점   G47813  ...  2.632010e+24      금곡동디온빌   \n",
       "151761    Q01A05   해장국/감자탕   I56111  ...  2.632010e+24  율리벽산블루밍아파트   \n",
       "151792    F15A02  미장타일도배도장      NaN  ...  2.632010e+24         NaN   \n",
       "151961    D02A02    꽃집/꽃배달   G47851  ...  2.632010e+24  금곡2단지주공아파트   \n",
       "152063    R10A01       독서실   R90212  ...  2.632010e+24        삼화빌딩   \n",
       "\n",
       "                          도로명주소   구우편번호    신우편번호   동정보  층정보  호정보          경도  \\\n",
       "33       부산광역시 북구 금곡대로616번길 142  616810  46505.0   NaN  NaN  NaN  129.017912   \n",
       "112           부산광역시 북구 금곡대로 712  616810  46510.0   NaN  NaN  NaN  129.018756   \n",
       "233     부산광역시 북구 금곡대로616번길 10-5  616762  46507.0   NaN  NaN  NaN  129.015256   \n",
       "263         부산광역시 북구 화명신도시로 244  616775  46520.0   208  NaN  NaN  129.011425   \n",
       "333           부산광역시 북구 금곡대로 458  616813  46509.0   NaN    2  NaN  129.013319   \n",
       "...                         ...     ...      ...   ...  ...  ...         ...   \n",
       "151739     부산광역시 북구 효열로219번다길 3  616810  46506.0   NaN  NaN  NaN  129.017838   \n",
       "151761           부산광역시 북구 효열로 1  616841  46509.0    상가  NaN  NaN  129.013943   \n",
       "151792    부산광역시 북구 효열로203번가길 39  616810  46506.0   NaN    2  NaN  129.017314   \n",
       "151961  부산광역시 북구 금곡대로616번길 10-7  616762  46507.0  7701  NaN  NaN  129.015221   \n",
       "152063        부산광역시 북구 금곡대로 441  616841  46519.0   NaN    5  NaN  129.012664   \n",
       "\n",
       "               위도  \n",
       "33      35.266739  \n",
       "112     35.270076  \n",
       "233     35.261768  \n",
       "263     35.245269  \n",
       "333     35.249129  \n",
       "...           ...  \n",
       "151739  35.264342  \n",
       "151761  35.248925  \n",
       "151792  35.264599  \n",
       "151961  35.261597  \n",
       "152063  35.247728  \n",
       "\n",
       "[677 rows x 39 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sub_df = df.loc[df['행정동명'].isin(['주례동','가야동','금곡동'])]\n",
    "\n",
    "sub_df.head(3)  #.head(3) 위에서부터 3개만 출력\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "0f6fc518",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>위도</th>\n",
       "      <th>경도</th>\n",
       "      <th>상호명</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>35.266739</td>\n",
       "      <td>129.017912</td>\n",
       "      <td>엑시아골프</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>35.270076</td>\n",
       "      <td>129.018756</td>\n",
       "      <td>동백주유소</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>233</th>\n",
       "      <td>35.261768</td>\n",
       "      <td>129.015256</td>\n",
       "      <td>향수&amp;화장품</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>263</th>\n",
       "      <td>35.245269</td>\n",
       "      <td>129.011425</td>\n",
       "      <td>형제식품</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>333</th>\n",
       "      <td>35.249129</td>\n",
       "      <td>129.013319</td>\n",
       "      <td>이편한낚시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151739</th>\n",
       "      <td>35.264342</td>\n",
       "      <td>129.017838</td>\n",
       "      <td>건미수다올</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151761</th>\n",
       "      <td>35.248925</td>\n",
       "      <td>129.013943</td>\n",
       "      <td>땅스부대찌개부산</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151792</th>\n",
       "      <td>35.264599</td>\n",
       "      <td>129.017314</td>\n",
       "      <td>이선산업</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151961</th>\n",
       "      <td>35.261597</td>\n",
       "      <td>129.015221</td>\n",
       "      <td>영진이엔에스</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>152063</th>\n",
       "      <td>35.247728</td>\n",
       "      <td>129.012664</td>\n",
       "      <td>화이트펜슬부산</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>677 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "               위도          경도       상호명\n",
       "33      35.266739  129.017912     엑시아골프\n",
       "112     35.270076  129.018756     동백주유소\n",
       "233     35.261768  129.015256    향수&화장품\n",
       "263     35.245269  129.011425      형제식품\n",
       "333     35.249129  129.013319     이편한낚시\n",
       "...           ...         ...       ...\n",
       "151739  35.264342  129.017838     건미수다올\n",
       "151761  35.248925  129.013943  땅스부대찌개부산\n",
       "151792  35.264599  129.017314      이선산업\n",
       "151961  35.261597  129.015221    영진이엔에스\n",
       "152063  35.247728  129.012664   화이트펜슬부산\n",
       "\n",
       "[677 rows x 3 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sub_df[['위도','경도','상호명']]  #위도, 경도, 상호명 확인"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67b6ce54",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
