# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WE9td2gL_X1h9Aiox9JJabdabKMHrZRK
"""

#필요모듈 import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# pc 파일을 코랩에 업로드 
from google.colab import files
uploaded = files.upload() # 파일 업로드 기능 실행

df = pd.read_csv('전주시 CCTV 설치 정보.csv', encoding='cp949')

# df.head(3)
pd.Series(df.columns)

import folium

latitude = 35.823832  #위도
longitude = 127.147718 #경도

m = folium.Map(location=[latitude, longitude],
               zoom_start=17, 
               width=750, 
               height=500
              )

# m

from folium.plugins import MarkerCluster

m = folium.Map(
    location=[latitude, longitude],
    zoom_start=15
)

coords = df[['위도','경도']]

marker_cluster = MarkerCluster().add_to(m)

for lat, long in zip(coords['위도'], coords['경도']):
    folium.Marker([lat, long], icon = folium.Icon(color='green')).add_to(marker_cluster)
    
m

